version: "3.1"
services:

  nginx:
    image: nginx:alpine
    container_name: symfony-nginx
    restart: always
    working_dir: /var/www/symfony
    volumes:
      - ./symfony/:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php-fpm:
    container_name: symfony-php-fpm
    build:
      context: docker/
      dockerfile: php-fpm/Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=pgsql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:3306/${POSTGRES_NAME}
    restart: always
    working_dir: /var/www/symfony
    volumes:
      - ./symfony/:/var/www/symfony
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini

  postgres:
    image: postgres:13.2-alpine
    container_name: symfony-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
      - ./pgscripts/:/tmp/scripts
    ports:
      - "5432:5432"